### ISSUE TITLE
Ask if would like to have `@colyseus/social` installed as well

### ISSUE THREAD

**Issue by endel** [colyseus/create-colyseus-app#4]
`@colyseus/social` requires MongoDB installed, which will throw errors if the developer doesn't have it installed on his environment.

Manually removing these lines solves this:

- https://github.com/colyseus/create-colyseus-app/blob/typescript/index.ts#L5
- https://github.com/colyseus/create-colyseus-app/blob/typescript/index.ts#L19

**Comment by alamboley** [comment]
Hi, is this related to:

```
iMac-Aymeric:my-colyseus-server aymeric$ npm start

> my-app@1.0.0 start /Users/aymeric/Desktop/Test/my-colyseus-server
> ts-node index.ts

Listening on ws://localhost:2567
(node:24777) DeprecationWarning: current Server Discovery and Monitoring engine is deprecated, and will be removed in a future version. To use the new Server Discover and Monitoring engine, pass option { useUnifiedTopology: true } to the MongoClient constructor.
Error connecting to database:  MongoNetworkError: failed to connect to server [127.0.0.1:27017] on first connect [Error: connect ECONNREFUSED 127.0.0.1:27017
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14) {
  name: 'MongoNetworkError',
  errorLabels: [Array],
  [Symbol(mongoErrorContextSymbol)]: {}
}]
    at Pool.<anonymous> (/Users/aymeric/Desktop/Gre/my-colyseus-server/node_modules/mongodb/lib/core/topologies/server.js:433:11)
    at Pool.emit (events.js:210:5)
    at Pool.EventEmitter.emit (domain.js:475:20)
    at /Users/aymeric/Desktop/Gre/my-colyseus-server/node_modules/mongodb/lib/core/connection/pool.js:562:14
    at /Users/aymeric/Desktop/Gre/my-colyseus-server/node_modules/mongodb/lib/core/connection/pool.js:985:11
    at /Users/aymeric/Desktop/Gre/my-colyseus-server/node_modules/mongodb/lib/core/connection/connect.js:40:11
    at callback (/Users/aymeric/Desktop/Gre/my-colyseus-server/node_modules/mongodb/lib/core/connection/connect.js:262:5)
    at Socket.<anonymous> (/Users/aymeric/Desktop/Gre/my-colyseus-server/node_modules/mongodb/lib/core/connection/connect.js:287:7)
    at Object.onceWrapper (events.js:300:26)
    at Socket.emit (events.js:210:5)
    at Socket.EventEmitter.emit (domain.js:475:20)
    at emitErrorNT (internal/streams/destroy.js:92:8)
    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  name: 'MongoNetworkError',
  errorLabels: [ 'TransientTransactionError' ],
  [Symbol(mongoErrorContextSymbol)]: {}
}
```

Note that I've: 
```
iMac-Aymeric:my-colyseus-server aymeric$ mongo
MongoDB shell version v4.2.1
````

Not sure what is wrong.

**Comment by endel** [comment]
Hi @alamboley, by the error message it seems MongoDB wasn't running when the app has started (`Error: connect ECONNREFUSED 127.0.0.1:27017`)

Do you still have this error after having mongodb running locally and restarting the app?

**Comment by alamboley** [comment]
@endel indeed, that was the MongoDB process not running. Thanks for the help.

**Comment by endel** [comment]
The @colyseus/social routes are now commented out by default. You can uncomment them if you'd like to use it as built-in authentication
